"use client";

import React, { useState, useEffect, useMemo } from 'react';
import { AppShell, type SectionID } from '@/components/layout/AppShell';
import { MotionStage } from '@/components/canvas/MotionStage';
import { AITerminal } from '@/components/terminal/AITerminal';
import { LiveInspector } from '@/components/panels/LiveInspector';
import { generateSvgMotionFromPrompt, type GenerateSvgMotionFromPromptOutput } from '@/ai/flows/generate-svg-motion-from-prompt';
import { useToast } from '@/hooks/use-toast';
import { 
  Sparkles, 
  Wand2, 
  ChevronRight, 
  Layers, 
  Activity,
  Zap
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useUser, useFirestore, useDoc, useCollection } from '@/firebase';
import { doc, collection, addDoc, query, orderBy, limit, serverTimestamp } from 'firebase/firestore';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { useResilienceStore } from '@/lib/ai/resilience-store';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';
import { cn } from '@/lib/utils';

export default function Home() {
  const [activeSection, setActiveSection] = useState<SectionID>('stage');
  const [result, setResult] = useState<GenerateSvgMotionFromPromptOutput | null>(null);
  const [localHistory, setLocalHistory] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  
  const { 
    status, 
    isFallbackActive, 
    cooldownRemaining, 
    triggerFallback, 
    tickCooldown 
  } = useResilienceStore();

  const { user } = useUser();
  const db = useFirestore();
  const { toast } = useToast();

  const userProfileRef = useMemo(() => (user && db) ? doc(db, 'users', user.uid) : null, [user, db]);
  const generationsRef = useMemo(() => (user && db) ? collection(db, 'users', user.uid, 'generations') : null, [user, db]);
  const historyQuery = useMemo(() => generationsRef ? query(generationsRef, orderBy('createdAt', 'desc'), limit(20)) : null, [generationsRef]);

  const { data: profile } = useDoc(userProfileRef);
  const { data: firestoreHistory } = useCollection(historyQuery);
  
  // Cooldown Timer Logic
  useEffect(() => {
    if (cooldownRemaining > 0) {
      const timer = setInterval(() => tickCooldown(), 1000);
      return () => clearInterval(timer);
    }
  }, [cooldownRemaining, tickCooldown]);

  const handleGenerate = async (promptText: string) => {
    if (!promptText.trim()) return;
    setIsLoading(true);
    setActiveSection('stage');

    // The Server Action now catches all errors and returns a valid result (AI or Fallback)
    const output = await generateSvgMotionFromPrompt({ prompt: promptText });
    
    if (output.isFallback) {
      triggerFallback();
      toast({
        variant: "destructive",
        title: "RESILIENCE ACTIVE",
        description: "Engine constraint detected. Stabilizing with procedural synthesis.",
      });
    } else {
      toast({
        title: "SYNTHESIS SUCCESS",
        description: "Elite vector topology generated by Gemini Engine.",
      });
    }

    saveResult(output, promptText, output.isFallback);
    setIsLoading(false);
  };

  const saveResult = (output: GenerateSvgMotionFromPromptOutput, promptText: string, isFallback = false) => {
    setResult(output);
    const generationData = {
      ...output,
      timestamp: Date.now(),
      prompt: promptText,
      isFallback
    };

    if (generationsRef && user) {
      addDoc(generationsRef, {
        ...generationData,
        createdAt: serverTimestamp(),
        userId: user.uid
      }).catch(err => {
        if (err.code === 'permission-denied') {
          errorEmitter.emitPermissionError(new FirestorePermissionError({
            path: generationsRef.path,
            operation: 'create',
            requestResourceData: generationData
          }));
        }
      });
    } else {
      setLocalHistory(prev => [{ ...generationData, id: Math.random().toString() }, ...prev]);
    }
  };

  const combinedHistory = useMemo(() => {
    const fHistory = firestoreHistory || [];
    return [...fHistory, ...localHistory].sort((a, b) => (b.timestamp || 0) - (a.timestamp || 0));
  }, [firestoreHistory, localHistory]);

  const renderContent = () => {
    switch (activeSection) {
      case 'stage':
        return (
          <div className="flex-1 flex flex-col relative h-full">
            <header className="h-14 glass-darker border-b border-white/5 px-6 flex items-center justify-between z-50">
              <div className="flex items-center gap-4">
                <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white/5 border border-white/10">
                  <div className={cn(
                    "w-2.5 h-2.5 rounded-full animate-pulse", 
                    status === 'operational' ? "bg-emerald-500 glow-accent" : "bg-amber-500 shadow-[0_0_10px_rgba(245,158,11,0.5)]"
                  )} />
                  <span className="text-[10px] font-code uppercase tracking-widest text-muted-foreground">
                    {isFallbackActive ? "Local Resilience Engine v2.0" : "Elite Gemini Engine v5.0"}
                  </span>
                </div>
                {isFallbackActive && (
                  <Badge variant="outline" className="border-amber-500/50 text-amber-500 text-[8px] gap-1 px-2 animate-pulse">
                    <Activity className="w-3 h-3" />
                    RESILIENCE ACTIVE {cooldownRemaining > 0 && `(${cooldownRemaining}s)`}
                  </Badge>
                )}
                <ChevronRight className="w-4 h-4 text-white/20" />
                <h1 className="text-xs font-headline font-bold uppercase tracking-[0.2em] text-foreground truncate max-w-[200px]">
                  {result ? result.title : "Active Pipeline"}
                </h1>
              </div>

              <div className="flex items-center gap-2">
                <Button size="sm" variant="ghost" className="h-8 text-[10px] gap-2 text-muted-foreground hover:text-primary uppercase tracking-widest font-headline" onClick={() => setActiveSection('history')}>
                  <Layers className="w-3.5 h-3.5" />
                  Archives
                </Button>
                <div className="w-px h-4 bg-white/10 mx-2" />
                <Button size="sm" className="h-8 text-[10px] gap-2 bg-primary hover:bg-primary/90 glow-primary uppercase tracking-widest font-headline" onClick={() => toast({ title: "BLUEPRINT SEALED" })}>
                  <Sparkles className="w-3.5 h-3.5" />
                  Deploy
                </Button>
              </div>
            </header>

            <div className="flex-1 relative">
              <MotionStage svgContent={result?.svg || ''} gsapCode={result?.gsap || ''} cssContent={result?.css || ''} isLoading={isLoading} />
              {!result && !isLoading && (
                <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none p-6 text-center">
                  <div className="w-20 h-20 bg-primary/10 rounded-3xl flex items-center justify-center mb-6 border border-primary/20 glow-primary">
                    <Wand2 className="w-10 h-10 text-primary" />
                  </div>
                  <h2 className="text-3xl font-headline font-bold tracking-tight text-glow mb-2">Cinematic Intelligence.</h2>
                  <p className="text-muted-foreground max-w-md">Invoke the zero-failure engine to synthesize world-class motion blueprints.</p>
                </div>
              )}
            </div>

            <div className="p-8 pb-10 z-50">
              <AITerminal onGenerate={handleGenerate} isLoading={isLoading} isQuotaWarning={isFallbackActive} />
            </div>
          </div>
        );
      case 'history':
        return (
          <div className="flex-1 p-8 space-y-8 flex flex-col overflow-hidden">
            <header className="flex items-center justify-between">
              <div>
                <h2 className="text-3xl font-headline font-bold tracking-tight text-glow">Vector Archives</h2>
                <p className="text-muted-foreground">Historical motion blueprints and resilience logs.</p>
              </div>
              <Button variant="outline" size="sm" onClick={() => setActiveSection('stage')} className="text-[10px] uppercase tracking-widest gap-2">
                Back to Stage
              </Button>
            </header>
            <ScrollArea className="flex-1">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 pb-12">
                {combinedHistory.map((item, idx) => (
                  <Card key={item.id || idx} className="glass-darker border-white/5 p-6 hover:border-primary/20 transition-all flex gap-6 overflow-hidden group">
                    <div className="w-32 h-32 rounded-lg bg-black/40 border border-white/5 flex items-center justify-center overflow-hidden shrink-0 group-hover:bg-primary/5 transition-colors">
                      <div className="scale-[0.25] pointer-events-none" dangerouslySetInnerHTML={{ __html: item.svg }} />
                    </div>
                    <div className="flex-1 space-y-4">
                      <div className="flex items-center justify-between">
                        <h3 className="text-xs font-bold uppercase tracking-widest text-primary truncate max-w-[150px]">{item.title}</h3>
                        {item.isFallback && <Badge className="text-[8px] bg-amber-500/10 text-amber-500 border-amber-500/20">RESILIENCE</Badge>}
                      </div>
                      <p className="text-[10px] text-muted-foreground italic line-clamp-2">"{item.prompt}"</p>
                      <Button variant="outline" size="sm" className="w-full text-[10px] uppercase tracking-widest border-white/10 hover:bg-primary/10 hover:text-primary" onClick={() => {
                        setResult(item);
                        setActiveSection('stage');
                      }}>Restore Fragment</Button>
                    </div>
                  </Card>
                ))}
                {combinedHistory.length === 0 && (
                  <div className="col-span-full py-20 text-center glass border-dashed border-white/10 rounded-3xl">
                    <Activity className="w-12 h-12 text-white/10 mx-auto mb-4" />
                    <p className="text-muted-foreground uppercase tracking-widest text-xs">No archives detected in current session.</p>
                  </div>
                )}
              </div>
            </ScrollArea>
          </div>
        );
      case 'profile':
        return (
          <div className="flex-1 p-8 space-y-12 max-w-5xl mx-auto w-full overflow-auto">
            <header className="flex items-end gap-8 pb-12 border-b border-white/5">
              <Avatar className="w-32 h-32 rounded-2xl border-2 border-white/10 glow-primary">
                <AvatarImage src={user?.photoURL || ''} />
                <AvatarFallback className="bg-primary/10 text-primary text-4xl">{user?.displayName?.charAt(0) || 'U'}</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <h2 className="text-4xl font-headline font-bold text-glow">{user?.displayName || 'Vanguard Entity'}</h2>
                <Badge className="bg-primary/20 text-primary mt-4 uppercase tracking-widest text-[10px]">{profile?.plan || 'Elite Free'}</Badge>
              </div>
            </header>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Card className="glass p-6 space-y-6">
                <h4 className="font-headline font-bold text-lg">Infrastructure Integrity</h4>
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-muted-foreground uppercase tracking-widest">Gemini Engine</span>
                    <Badge className={cn(status === 'operational' ? "bg-emerald-500/10 text-emerald-500" : "bg-amber-500/10 text-amber-500")}>
                      {status === 'operational' ? "OPERATIONAL" : "DEGRADED"}
                    </Badge>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-muted-foreground uppercase tracking-widest">Resilience Fallback</span>
                    <Badge className="bg-emerald-500/10 text-emerald-500">READY</Badge>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-muted-foreground uppercase tracking-widest">Session Cache</span>
                    <Badge variant="outline" className="border-white/10">{combinedHistory.length} bluebrints</Badge>
                  </div>
                </div>
              </Card>

              <Card className="glass p-6 space-y-6">
                <h4 className="font-headline font-bold text-lg">Engine Calibration</h4>
                <div className="space-y-4">
                  <p className="text-xs text-muted-foreground">Adjust your synthesis parameters for specialized kinetic output.</p>
                  <Button variant="outline" className="w-full text-[10px] uppercase tracking-widest gap-2" disabled>
                    Upgrade Infrastructure
                  </Button>
                </div>
              </Card>
            </div>
          </div>
        );
      default:
        return null;
    }
  };

  return (
    <AppShell activeSection={activeSection} onSectionChange={setActiveSection}>
      <div className="flex h-full w-full overflow-hidden">
        {renderContent()}
        {activeSection === 'stage' && (
          <aside className="w-[400px] h-full hidden xl:block z-50">
            <LiveInspector result={result} />
          </aside>
        )}
      </div>
    </AppShell>
  );
}
